# Generated by Django 4.0.1 on 2022-02-05 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
